# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/zoomyboy/scoutnet/models/event/columns.yaml

# Model Class name
modelClass: Zoomyboy\Scoutnet\Models\Event
