# ===================================
#  Form Behavior Config
# ===================================

# Model Form Field configuration
form: $/zoomyboy/scoutnet/models/event/fields.yaml

# Model Class name
modelClass: Zoomyboy\Scoutnet\Models\Event
