# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Calendar

# Model Form Field configuration
form: $/zoomyboy/scoutnet/models/calendar/fields.yaml

# Model Class name
modelClass: Zoomyboy\Scoutnet\Models\Calendar

# Create page
create:
    title: Create
    flashSave: Calendar has been created!

# Update page
update:
    title: Edit
    redirect: zoomyboy/scoutnet/calendar
    flashDelete: Calendar has been deleted
